FROM osrf/ros:humble-desktop-full

SHELL ["/bin/bash", "-c"]
RUN apt-get update && apt-get install -y vim tree \
    && rm -rf /var/lib/apt/lists/*

# COPY config/ /site_config/

ARG USERNAME=small-thinking
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Create a non-root user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && mkdir -p /home/$USERNAME/.config && chown $User_UID:$USER_GID /home/$USERNAME/.config


# Setup sudo
RUN apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME \
    && rm -rf /var/lib/apt/lists/*